### ISSUE TITLE
Clipping of the JF-17 with the JAS39 body 

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#1]
I am assuming that the x-y-z needs to be adjusted so the left and right sides of the cockpit does not clip the airframe.

**Comment by FatSpacePanda** [comment]
fixed

**Comment by whisky-actual** [comment]
Can you merge the the new fix if not just pm me the fix

**Comment by FatSpacePanda** [comment]
> Can you merge the the new fix if not just pm me the fix

Its already merged but its not perfect, its a tradeoff between clipping in the sides and infront of the hud glass. Right now there is no clipping at the front and some clipping when moving your head close to the sides. It can probably be improved since you dont look behind the glass very often
