### ISSUE TITLE
Model floating

### ISSUE THREAD

**Issue by FatSpacePanda** [whisky-actual/Community-JAS-39-C#12]
Wheels do not connect with the ground with latest model

**Comment by FatSpacePanda** [comment]
I have tried to change gear_pos without success

**Comment by Ulvar40** [comment]
Strange! I dont have that  on my installation and I downloaded from the last link on the DCS forum.

**Comment by FatSpacePanda** [comment]
> Strange! I dont have that on my installation and I downloaded from the last link on the DCS forum.

I used an older version of the model on that link, new model has more working features but collision box is a bit off

**Comment by FatSpacePanda** [comment]
currently working on a new collision shell
