### ISSUE TITLE
Replace gun with BK 27 and correct ammo

### ISSUE THREAD

**Issue by currenthill** [whisky-actual/Community-JAS-39-C#14]
Replace the JF-17 Gsh23 with BK 27 (Akan m/85) gun with the correct ammo type and combination.

**Comment by currenthill** [comment]
Gun work is done. Need somewhere to place the lua updates.

**Comment by FatSpacePanda** [comment]
> Gun work is done. Need somewhere to place the lua updates.

We are working on a good solution to share files worked on

**Comment by whisky-actual** [comment]
What's the file name you can make the edits directly here if you want. I'll try to give you a few hints how to do this. If not you can pm the file and I'll put it up.

**Comment by whisky-actual** [comment]
Can we close this issue?
