### ISSUE TITLE
Implement choice between gun ammo types

### ISSUE THREAD

**Issue by currenthill** [whisky-actual/Community-JAS-39-C#15]
Implement the choice between Gripens combat mix and the newer FAP (frangible armour piercing) shells.

**Comment by currenthill** [comment]
Gun work is done. You can now choose ammo type, AM BAND 06 or AM BAND 07 which are the Swedish ammo configurations. Need somewhere to put the updated lua files.

**Comment by whisky-actual** [comment]
Great job, maybe you can post the file name then you can copy paste the code directly into it! If it's a new files I sent you some info on Discord.
