### ISSUE TITLE
New sounds for Bitching Betty

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#16]
Add new custom sounds for the cockpit warnings.

**Comment by Ulvar40** [comment]
One possibility is that we record our own sound! But do we have any information all the voice is a male?

**Comment by whisky-actual** [comment]
Yep a video that Double Tap posted on the discord.

**Comment by Ulvar40** [comment]
First version

[Pullup.zip](https://github.com/whisky-actual/Community-JAS-39-C/files/6055312/Pullup.zip)

**Comment by whisky-actual** [comment]
I've added your sounds from the .zip to the main install keep them coming!
