### ISSUE TITLE
Fins of agm 88 harm is clipping pylon when x2 on one pylon

### ISSUE THREAD

**Issue by FatSpacePanda** [whisky-actual/Community-JAS-39-C#17]

**Comment by whisky-actual** [comment]
Did we fix this?

**Comment by FatSpacePanda** [comment]
> Did we fix this?

No we would need another shape for ld-10. I say we either remove the double ld10 or leave it, for now

**Comment by whisky-actual** [comment]
> > Did we fix this?
> 
> No we would need another shape for ld-10. I say we either remove the double ld10 or leave it, for now

I am pretty sure we can adjust the position... Someone fixed the meteor on discord. Try @everyone and ask :)

**Comment by FatSpacePanda** [comment]
> > > Did we fix this?
> > 
> > 
> > No we would need another shape for ld-10. I say we either remove the double ld10 or leave it, for now
> 
> I am pretty sure we can adjust the position... Someone fixed the meteor on discord. Try @everyone and ask :)

that was me. The fins on the harm are too large

**Comment by whisky-actual** [comment]
Ok 1 per pylon will that work?

**Comment by FatSpacePanda** [comment]
> Ok 1 per pylon will that work?

Yes one works fine. Its just the two that gets too wide when they sit next to each other

**Comment by whisky-actual** [comment]
Ok, I know the F18 and F16 can only have 1 per pylon... We should do the same for the JAS39

**Comment by FatSpacePanda** [comment]
> Ok, I know the F18 and F16 can only have 1 per pylon... We should do the same for the JAS39

I will remove the 2x harms
