### ISSUE TITLE
Add hardpoints for TGP and integrated EWS

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#2]
Currently need to move the stations around to make the cheek work for TPod. Then add a new station for the centerline.

**Comment by whisky-actual** [comment]
Not sure if this is still an issue, did we get all hard points to work?

**Comment by currenthill** [comment]
WIP. I will disable the extra hardpoints from the master until we have figured this out. We have a couple of ideas to test.
