### ISSUE TITLE
Rework jf17 mfds and hud to look like gripen

### ISSUE THREAD

**Issue by FatSpacePanda** [whisky-actual/Community-JAS-39-C#23]

**Comment by whisky-actual** [comment]
Do you have any source data? Maybe double tap can help out

**Comment by Ulvar40** [comment]
![2560-3833-By-Angad](https://user-images.githubusercontent.com/79517219/109412335-9a4a6c00-79a7-11eb-9e63-30ecf9aadf43.jpg)
![zaJuyTX](https://user-images.githubusercontent.com/79517219/109412336-9ae30280-79a7-11eb-8d8e-59ea8ea33c44.jpg)

**Comment by Ulvar40** [comment]
But... I found a lot of pictures that might indicate that the export version have different colors in the MFD´s

**Comment by whisky-actual** [comment]
@Ulvar40 if you have high resolution versions drop them in the pictures sections of the document on the GitHub
