### ISSUE TITLE
3D modeling of new gripen model + animations

### ISSUE THREAD

**Issue by FatSpacePanda** [whisky-actual/Community-JAS-39-C#25]

**Comment by whisky-actual** [comment]
@FatSpacePanda are we talking about the D model?

**Comment by FatSpacePanda** [comment]
> @FatSpacePanda are we talking about the D model?

D and new C model

**Comment by whisky-actual** [comment]
Ok your are sharing the task? Or you are doing it on your own?

**Comment by FatSpacePanda** [comment]
> Ok your are sharing the task? Or you are doing it on your own?

Oh, Im not doing any of them I just added this so that we can keep track of whats i the works

**Comment by whisky-actual** [comment]
@Breadmaker91 are you still with us? Or you are focused on something else the moment?

**Comment by FatSpacePanda** [comment]
> @Breadmaker91 are you still with us? Or you are focused on something else the moment?

I think he is working on our cockpit atm
