### ISSUE TITLE
Make the AG weapons work

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#34]

**Comment by FatSpacePanda** [comment]
All guided Missiles

**Comment by whisky-actual** [comment]
Started testing sheet is here https://docs.google.com/spreadsheets/d/1ocx7OoqZa4EiH8DLde3pvrf5t6iXTTck1N7LuauKgzQ/edit?usp=sharing

**Comment by FatSpacePanda** [comment]
We need to decide between tv guided, laser guided that requires buddy lase or over-powered laser bombs ( essentially missiles )
