### ISSUE TITLE
Replace the aim120D with the meteor and the aim9x with the iris-t

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#4]
User will need to choose between the 2 models. Would be nice to have both.

**Comment by FatSpacePanda** [comment]
Metor is added right? can we close this?

**Comment by whisky-actual** [comment]
Can you help me to add them to the FC3 mod? Is there a way not to overwrite the 120c ?

**Comment by currenthill** [comment]
New Meteor missile added.

**Comment by whisky-actual** [comment]
Thanks, can we now load the 120b also?

**Comment by Talocan1** [comment]
Is the Meteor downloadble somewhere? Sorry, I have no experience with GitHub

**Comment by currenthill** [comment]
I'm adding the Rb74 (Aim-9L) and Rb99 (Aim-120B) as separate choices to the Rb98 and Rb101. 

Just need to do some more testing before commit. Then we can close this one.

**Comment by FatSpacePanda** [comment]
> I'm adding the Rb74 (Aim-9L) and Rb99 (Aim-120B) as separate choices to the Rb98 and Rb101. 
> 
> Just need to do some more testing before commit. Then we can close this one.  

Awesome! Are you sure the sms system wont fuss?

**Comment by currenthill** [comment]
Well, it is what it is. They will naturally show up as unknown, but there's no problem firing them. That'll probably be good enough for now. I we find a way to tweak the SMS down the line we'll revisit and polish it.

Gripen firing old school loadout:
https://youtu.be/sSQH4dCfgz8

**Comment by FatSpacePanda** [comment]
> Well, it is what it is. They will naturally show up as unknown, but there's no problem firing them. That'll probably be good enough for now. I we find a way to tweak the SMS down the line we'll revisit and polish it.
> 
> 
> 
> Gripen firing old school loadout:
> 
> https://youtu.be/sSQH4dCfgz8
> 
> 

Niiice! I thought anything not recognized by sms wouldn't work

**Comment by currenthill** [comment]
Rb99 (Aim-120B) has been added to JF version.

**Comment by whisky-actual** [comment]
Would it be now possibly add them to the f15 version?

**Comment by FatSpacePanda** [comment]
> Would it be now possibly add them to the f15 version?

Did you get a chance to try out the fc3?

**Comment by whisky-actual** [comment]
yep i did and it works :)
