### ISSUE TITLE
Add braking with W key

### ISSUE THREAD

**Issue by FatSpacePanda** [whisky-actual/Community-JAS-39-C#45]

**Comment by FatSpacePanda** [comment]
![tgp overlayed text](https://user-images.githubusercontent.com/79235868/121032764-dd3c8c80-c7ab-11eb-821c-8927d0751e42.png)

**Comment by FatSpacePanda** [comment]
Script done. Initial testing show positive results

**Comment by CIChesty** [comment]
New wheel brake bind works great on A/A Gripen.

**Comment by DJTaz1975** [comment]
yes works great on A/A. Brake effect on slow speed is high but if that's how it should be then its fine. But make it a bit jerky doing slow taxi and breaking but I guess its something to adapt to.

**Comment by FatSpacePanda** [comment]
> yes works great on A/A. Brake effect on slow speed is high but if that's how it should be then its fine. But make it a bit jerky doing slow taxi and breaking but I guess its something to adapt to.

Noted👍. The brakes are only on/off as of now, it just allows you to bind the binary fc3 brake to an axis. I think we need the efm to get dynamic braking force

**Comment by DJTaz1975** [comment]
"Borrow" it from F-15 and tweak it to fit JAS? :)

**Comment by FatSpacePanda** [comment]
> "Borrow" it from F-15 and tweak it to fit JAS? :)

I don't think F-15 has it
