### ISSUE TITLE
Incompatible with 2.5.5 stable version

### ISSUE THREAD

**Issue by opa79** [whisky-actual/Community-JAS-39-C#47]
Addon is incompatible with DCS 2.5.5 version. 
Errors are in lights section of JAS39GripenXX.lua files. Then, when indices are fixed ( [WOLALIGHT_XX] are replaced with [1], [2], etc.), weapons fail to load.

**Comment by chazmat** [comment]
You're joking, right?

**Comment by whisky-actual** [comment]
Sorry mate, you will need to update. We can't support old branches
