### ISSUE TITLE
Add all the proper ordinance

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#5]
Will need to check what's available for each station.

**Comment by FatSpacePanda** [comment]
Just to add: What weapons we can put on the plane without issues with SMS system and what pylons can carry what. Guessing pylons are limited by weight IRL

**Comment by FatSpacePanda** [comment]
wip

**Comment by whisky-actual** [comment]
@FatSpacePanda coordinate with @currenthill we should finish this task first it's and easy one and with that out of the way we can focus with the rest!

**Comment by currenthill** [comment]
We could go authentic or get wild and modernize some of it. Or both, as separate versions. 

This is the weaponry the Swedish 39C has been certified for during its current lifespan.

![JAS 39C Gripen Swedish Loadout](https://user-images.githubusercontent.com/69079101/109415744-c02d3c00-79ba-11eb-9868-7e340a2dd32f.png)

This is what I would suggest for a more modernized configuration. I started with the most modern of the 39C weaponry, added both current and planned from E/F and filled in some blanks (for example, the Gripen doesn't have anti-radiation missiles).

![JAS 39C Gripen Modern Loadout](https://user-images.githubusercontent.com/69079101/109415780-071b3180-79bb-11eb-9145-5c506c59b4dc.png)

**Comment by currenthill** [comment]
My plan is to add and tune weapon by weapon and then as a last step clean up and restructure the loadout in the base LUA.

**Comment by whisky-actual** [comment]
Great stuff, thanks @currenthill !

**Comment by currenthill** [comment]
IRIS-T has been added to the JF version.

**Comment by currenthill** [comment]
I'm going to close this issue and replace it with separate issues related to the different remaining weapons. 

At the time of closing of this issue the following weapons are implemented:

- AKAN M85 BK 27
- Rb74 AIM-9L
- Rb98 IRIS-T
- Rb99 AIM-120B
- Rb101 Meteor
- Rb75 AGM-65B
- GBU-12
- ARAK M70B AP
- ARAK M70B HE
- Rb15F Mk3
- LDP Litening III
- External drop tank 1100 litre
