### ISSUE TITLE
MAR.1 Cruising speed (ALPHA RELEASE BEFORE 15 JUNE RELEASE)

### ISSUE THREAD

**Issue by CJordense** [whisky-actual/Community-JAS-39-C#53]
I tested out the MAR.1 HARM Missiles earlier when the Gripen released, only to see thet their Cruising Speed is **5000 knots**. It's in order of the screenshots: 1. Just fired, 2. Acceleration till it stops accelerating for 2-3 seconds, 3. Accelerates till 5000 knots, 4. Closing in on sam site at lot's of G's.

When turning towards the target (in this case a HAWK sam site), it pulled 40 G's constant for about 3 seconds. 
I'll post the screenshots in this post below. Check the infobar at the bottom of the screen for info on the missile ongoing. It displays speed, alt and G's. Cheers, CJ.
![Screen_210615_185657](https://user-images.githubusercontent.com/85957412/122094782-d4cbfd80-ce0c-11eb-878f-7a353c810e76.png)
![Screen_210615_185719](https://user-images.githubusercontent.com/85957412/122094787-d5649400-ce0c-11eb-872e-ddc465a755cc.png)
![Screen_210615_185737](https://user-images.githubusercontent.com/85957412/122094790-d5fd2a80-ce0c-11eb-9f78-3fc90c0b05a2.png)
![Screen_210615_185745](https://user-images.githubusercontent.com/85957412/122094793-d695c100-ce0c-11eb-9150-28d2b7c92c5a.png)
![Screen_210615_185757](https://user-images.githubusercontent.com/85957412/122094794-d695c100-ce0c-11eb-8cf8-058ba0a9230e.png)

**Comment by whisky-actual** [comment]
Good stuff, did Vinedog already share the dev build because this is already fixed

**Comment by CJordense** [comment]
> Good stuff, did Vinedog already share the dev build because this is already fixed

So, this was before the new one dropped, I guess I'll have to test it out then. 
Check tomorrow.
