### ISSUE TITLE
HUD Reflection Jittering when turning/pitching.

### ISSUE THREAD

**Issue by CJordense** [whisky-actual/Community-JAS-39-C#54]
https://user-images.githubusercontent.com/85957412/122261969-322b8180-ced5-11eb-83f8-d0dd107d2385.mp4

**Comment by DJTaz1975** [comment]
Can confirm this is the case.  tested it today.

**Comment by DJTaz1975** [comment]
Suggestion: can this reflection feature be removed completely? for me I dont see the point of having it. harder to read the screens but yes it adds realism with reflections. so I guess its a personal preference

**Comment by whisky-actual** [comment]
We will investigate ,thx

**Comment by DJTaz1975** [comment]
@whisky-actual question, is it possible to make the reflections not so sharp? I checked the f-16 reflections and its a lot less reflections but its there. reflections adds realism but if it could be tuned down that would be better I think. but not sure if this can be customized?

**Comment by whisky-actual** [comment]
> @whisky-actual question, is it possible to make the reflections not so sharp? I checked the f-16 reflections and its a lot less reflections but its there. reflections adds realism but if it could be tuned down that would be better I think. but not sure if this can be customized?

We can try, the whole cockpit is being re-texture so that will be addressed
