### ISSUE TITLE
Remove directory structure for easy update

### ISSUE THREAD

**Issue by FalcoGer** [whisky-actual/Community-JAS-39-C#55]
Currently the github project includes the directory structure for `Mods/aircraft`, however if you wanted to use git to keep the mod updated this is an issue as saved `games/dcs[.openbeta]` would need to be the root folder, allowing for no other git as well as forcing all those non related files into the local repository.

On top of that that makes working and developing the mod more difficult as you will have to copy any modifications to the saved games/dcs directory before testing instead of just changing something and then testing right then and there.

I propose that only the grippen folder be included in this repository as the root directory with updated instructions on installation in the readme file. (aka you clone into mods/aircraft/grippen, the .git folder then being inside grippen.)

This will allow multiple mods being managed in such a manner and ease testing changes.

**Comment by richstav** [comment]
> 
> 
> Currently the github project includes the directory structure for `Mods/aircraft`, however if you wanted to use git to keep the mod updated this is an issue as saved `games/dcs[.openbeta]` would need to be the root folder, allowing for no other git as well as forcing all those non related files into the local repository.
> 
> On top of that that makes working and developing the mod more difficult as you will have to copy any modifications to the saved games/dcs directory before testing instead of just changing something and then testing right then and there.
> 
> I propose that only the grippen folder be included in this repository as the root directory with updated instructions on installation in the readme file. (aka you clone into mods/aircraft/grippen, the .git folder then being inside grippen.)
> 
> This will allow multiple mods being managed in such a manner and ease testing changes.

Absolutely, agree with this. To the team, great work, and it was nice to see a DCS aircraft on github for easy updates.

**Comment by whisky-actual** [comment]
If we don't keep it as-is people will need to create the Mods/aircraft/ when they d/l the mod. Currently, you just drop the folder in your DCS folder in your saved game which can or cannot be called dcs.open beta or the stable version. Finally, just a small fraction of people use GitHub as a tool. We will consider the pro's and cons

**Comment by FalcoGer** [comment]
For those that do not use github, there is the release download or a download from eagle dynamic user files.
