### ISSUE TITLE
New base texture with updated roughmap and UV

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#6]
New textures, possible 4k?

**Comment by DoubleTap37** [comment]
I'm currently working on a new skin set, with new realistic screws, rivets, weathering lines, details etc. I'll upload a PSD template for it, for everyone to have a look at / use for their own skin versions.

**Comment by whisky-actual** [comment]
Keep us posted, looking forward to this!
