### ISSUE TITLE
missing keybinds

### ISSUE THREAD

**Issue by pighunters** [whisky-actual/Community-JAS-39-C#61]
i have a problem i am missing the weapon fire keybind on the gripen

**Comment by whisky-actual** [comment]
Can you be more precise? Just to be clear there is no pickle button in the JAS-39, the trigger weapon changes depending on the mode you are in.

**Comment by smully1** [comment]
For me, the trigger doesn't do anything, tutorials just say hold weapon launch, but holding trigger does nothing

**Comment by whisky-actual** [comment]
Try looking at these videos: https://www.youtube.com/playlist?list=PLXSVG_BMY5bANATSqZzH9osrnklae_8wg

**Comment by bradthorn55** [comment]
> i have a problem i am missing the weapon fire keybind on the gripen

Same when i go to my controls it doesn't say anything like weapon release or weapon fire but if I go to Gripen weapons it says trigger and that also does nothing

**Comment by bradthorn55** [comment]
there is no weapon fire or weapon release on the controls only trigger but that also doesn't work when trying to fire a weapon.

**Comment by smully1** [comment]
I just realised that my master arm was off and that fixed it, it's on the right side of the cockpit

**Comment by bradthorn55** [comment]
I found it look on the right in the cockpit and it says live or something like that move it to on or live and you will be able to fire also trigger is the thing to dire any of your weapons.
