### ISSUE TITLE
Cockpit for Gripen

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#7]
Would be nice to add a special menu and have the option to select between the default and grey cockpit.

**Comment by DoubleTap37** [comment]
I think this can be done via the options menu in the UI, I'll have a look this evening and get back to you.

**Comment by whisky-actual** [comment]
I know we can do it, if you can't figure it out I'll look also!

**Comment by whisky-actual** [comment]
@DoubleTap37 did you figure it out? How to add this without overwriting the JF-17 files?

**Comment by whisky-actual** [comment]
We need to map FC3 functions to the MFDs
