### ISSUE TITLE
Can't control aircraft while using keyboard, responds so slowly that it basically doesnt respond

### ISSUE THREAD

**Issue by ronaldoks7** [whisky-actual/Community-JAS-39-C#73]
gripen a/g responds extremely slowly to arrow keys nor throttle, despite being set properly on keybinds, but switching modes on hud and changing weapons work fine. I can roll maybe 2 degrees and pitch 4 then that's it

**Comment by whisky-actual** [comment]
Known issues, mod is currently for joystick players
