### ISSUE TITLE
Ground units disappear

### ISSUE THREAD

**Issue by weldroid** [whisky-actual/Community-JAS-39-C#77]
I have noticed that whenever I have the Gripen mod installed under DCS (latest public beta), the ground armor units disappear. (e.g. Russian armor, BMPs, BTRs, etc.) They can still be added via the mission editor, but they do not show up in the 3D world.

**Comment by whisky-actual** [comment]
It's been pointed out before, most likely an issue with a combination with other mods.

**Comment by BlueFalcon069** [comment]
I believe the conflict is with the Lechuzas Negras Typhoon mod.
