### ISSUE TITLE
Have the canards maped with different arguments

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#8]
So we can animate them on landing for braking.

**Comment by FatSpacePanda** [comment]
We need to figure out if the jf17 uses the same argument for deployning and dropping the brake chute. Or if there are two different. 
CHUTE_PLAYER_DEPLOY = 611, value <=0 = no chute, value 1 = chute deployed
CHUTE_PLAYER_SHOW   = 612, value less than 0 = arg 611 has no effect, chute is gone

**Comment by whisky-actual** [comment]
I guess you and Neon figure that out. I'll try to help the best I can!
