### ISSUE TITLE
Add all positions lights, taxi,strobes and navigation

### ISSUE THREAD

**Issue by whisky-actual** [whisky-actual/Community-JAS-39-C#9]
Have them mapped so we can activate them in the JF-17 cockpit

**Comment by FatSpacePanda** [comment]
Position and taxi/landing are working. edit: Nav lights are working

**Comment by whisky-actual** [comment]
I guess you have the latest stuff, definately need to add this stuff :)

**Comment by FatSpacePanda** [comment]
got lights to work with current build

**Comment by whisky-actual** [comment]
Good, was this with the correct model. You can take the one in the FC3 it is the one not floating, but without the good Arg.

**Comment by FatSpacePanda** [comment]
> Good, was this with the correct model. You can take the one in the FC3 it is the one not floating, but without the good Arg.

this was with floating model

**Comment by whisky-actual** [comment]
Get the model from the FC3 folder and try it out. It works with the F15, should be ok with the JF-17 also
